[workspace]
members = ["poodio"]
resolver = "2"

[workspace.package]
edition = "2021"
license-file = "LICENSE"
repository = "https://github.com/AsherJingkongChen/poopoo"

[profile.release]
debug = false
lto = true
opt-level = "s"
panic = "abort"
strip = true
