[workspace]
members = ["poodio"]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/AsherJingkongChen/poopoo"
version = "0.0.0"
license-file = "LICENSE"

[profile.release]
debug = false
lto = true
opt-level = "s"
panic = "abort"
strip = true
