#! /usr/bin/env node

const C = require("node:child_process");
const loader = require("./loader.cjs");
const { bin, name, version } = require("../../package.json");

const pkgName = loader.buildPkgName(name);
loader.tryInstallPkg(pkgName, version);

const source = require.resolve(`${pkgName}/${bin}`);
const args = process.argv.slice(2);

C.execFileSync(source, args, { stdio: "inherit" });

// TODO: Replace stubs with the "source" package

