name: CI for poodio

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: ["main"]
        tags: ["poodio@[0-9]+.[0-9]+.[0-9]+"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/install-action@just
            - run: just prepare check
            - run: just check-dep
              # if: github.ref_type == 'tag'

    build:
        if: github.ref_type == 'tag'
        needs: check
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: macos-latest
                      target: common
                    - os: macos-latest
                      target: aarch64-apple-darwin
                    - os: macos-latest
                      target: x86_64-apple-darwin
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                    - os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                    - os: ubuntu-latest
                      target: i686-unknown-linux-gnu
                    - os: windows-latest
                      target: aarch64-pc-windows-msvc
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - os: windows-latest
                      target: i686-pc-windows-msvc
        steps:
            - uses: actions/checkout@v4
            - uses: taiki-e/setup-cross-toolchain-action@v1
              if: matrix.target != 'common'
              with:
                  target: ${{ matrix.target }}
            - name: Configure Cross-compilation for Ubuntu Linux
              if: matrix.os == 'ubuntu-latest'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y --no-install-recommends \
                    libasound2-dev

                  TARGET=""
                  case "${{ matrix.target }}" in
                    aarch64-*) TARGET="aarch64-linux-gnu" ;;
                    i686-*)    TARGET="i686-linux-gnu"    ;;
                  esac

                  if [[ -n "$TARGET" ]]; then
                    echo "PKG_CONFIG_PATH=/usr/lib/$TARGET/pkgconfig" >> $GITHUB_ENV
                    echo "PKG_CONFIG_SYSROOT_DIR=/" >> $GITHUB_ENV
                  fi
            - uses: taiki-e/install-action@just
            - run: |
                  just prepare poodio::build ${{ matrix.target }}
            - uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.target }}
                  path: poodio/dist/

    publish:
        if: github.ref_type == 'tag'
        needs: build
        runs-on: macos-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  path: dist/
            - name: Package GitHub Release Assets
              run: |
                  for dir in dist/*; do
                    [[ "$dir" == "dist/common" ]] && continue
                    target=$(basename "$dir");
                    cd "$dir/bin/"
                    tar -czf "poodio-$target.tgz" *
                    cd - > /dev/null
                  done
            - name: Publish to github.com
              uses: softprops/action-gh-release@v2
              with:
                  append_body: false
                  files: dist/*/bin/*.tgz
                  generate_release_notes: true
            - name: Publish to crates.io
              run: cargo publish --locked --package poodio --no-verify
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
            - name: Publish to npmjs.com
              run: |
                  echo "//registry.npmjs.org/:_authToken=${{ secrets.NPMJS_API_TOKEN }}" > .npmrc
                  for pkg in dist/*; do
                    npm publish --access public --provenance "./$pkg/npm/"
                  done
                  rm .npmrc
