name: CI for poodio

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: ["main"]
        tags: ["poodio@v[0-9]+.[0-9]+.[0-9]+"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - uses: actions/cache@v4
              with:
                  key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
            - uses: taiki-e/install-action@v2
              with:
                  tool: cargo-outdated
            - run: cargo outdated --exit-code 34
            - run: cargo fmt --all -- --check
            - run: cargo clippy --all-features -- -D warnings
            - run: cargo test --all-features

    build-github-release:
        if: github.ref_type == 'tag'
        needs: check
        runs-on: ${{ matrix.os }}
        permissions:
            contents: write
        strategy:
            matrix:
                include:
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      prefix: poodio
                      suffix:
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      prefix: poodio
                      suffix: .exe
                    - os: macos-latest
                      target: aarch64-apple-darwin
                      prefix: poodio
                      suffix:
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - uses: actions/cache@v4
              with:
                  key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
            - run: cargo build --locked --release --target ${{ matrix.target }}
            - run:
                  mv target/${{ matrix.target }}/release/${{ matrix.prefix }}${{ matrix.suffix }}
                  ${{ matrix.prefix }}-${{ matrix.target }}${{ matrix.suffix }}
            - uses: softprops/action-gh-release@v2
              if: github.ref_type == 'tag'
              with:
                  files: ${{ matrix.prefix }}-${{ matrix.target }}${{ matrix.suffix }}

    publish-crates-release:
        if: github.ref_type == 'tag'
        needs: check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - uses: actions/cache@v4
              with:
                  key: ${{ runner.os }}-${{ runner.arch }}-${{ hashFiles('**/Cargo.lock') }}
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
            - run: cargo publish --all-features --locked --package poodio
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
