name: CI for poodio

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
    push:
        branches: ["main"]
        tags: ["poodio@[0-9]+.[0-9]+.[0-9]+"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    check:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - uses: taiki-e/install-action@v2
              with:
                  tool: just
            - run: just prepare check

    test-tar:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: macos-latest
                      target: aarch64-apple-darwin
                      prefix: poodio
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
        steps:
            - run: tar --version
              shell: bash
            - run: zip --version
              shell: bash

    build-target:
        if: github.ref_type == 'tag'
        needs: check
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                include:
                    - os: macos-latest
                      target: aarch64-apple-darwin
                      prefix: poodio
                    - os: windows-latest
                      target: x86_64-pc-windows-msvc
                      prefix: poodio
                      suffix: .exe
                    - os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      prefix: poodio
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - uses: taiki-e/install-action@v2
              with:
                  tool: just
            - run: just prepare poodio::build-target ${{ matrix.target }}
            - name: Upload Artifacts for publish
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ matrix.target }}
                  path: poodio/dist

    publish:
        if: github.ref_type == 'tag'
        needs: build-target
        runs-on: macos-latest
        permissions:
            contents: write
            id-token: write
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 1
            - uses: actions/download-artifact@v4
              with:
                  path: dist
            - uses: softprops/action-gh-release@v2
              with:
                  files:
                  generate_release_notes: true
            # - run: cargo publish --all-features --locked --package poodio --no-verify
            #   env:
            #       CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}
            # - run: npm publish --provenance --access public
            #   env:
            #       NODE_AUTH_TOKEN: ${{ secrets.NPM_API_TOKEN }}
